First pass at variable quotas
flowforge/flowforge-file-server pull request #70
Opened 2023-08-23 14:18 UTC by hardillb

part of #66 
## Description

Allows quota values to be passed from the Forge App.

It gets the quota sizes for the team when it checks the token passed.

## Related Issue(s)

#66 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

2023-08-23 14:18 UTC, hardillb commented
This will depend on a second PR against the flowforge/flowforge project

2023-08-30 07:56 UTC, knolleary approved these changes

2023-08-30 09:22 UTC, knolleary requested changes
To match the proposed changes in the server side, this wraps the expected response in a `quota` object

2023-08-30 09:22 UTC, knolleary commented on forge/auth.js
> +                request.quota = tokenResponse
```suggestion
                request.quota = tokenResponse.quota
```

2023-08-30 09:22 UTC, knolleary commented on forge/auth.js
> +                    quota: tokenResponse
```suggestion
                    quota: tokenResponse.quota
```

2023-08-30 09:22 UTC, knolleary commented on test/unit/setup.js
> +                    res.end('{ "file": 1000, "context": 1000 }')
```suggestion
                    res.end('{ "quota": { "file": 1000, "context": 1000 } }')
```

2023-08-30 09:54 UTC, knolleary approved these changes

2023-08-30 09:54 UTC, merged